version: '3.7'

services:

  frontend:
    container_name: angl
    environment: 
      - Backend=http://127.0.0.1/4000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'

  backend:
    container_name: angl_back
    environment: 
      - Database=http://127.0.0.1/27017
    build:
      context: './backend'
      dockerfile: Backend-Dockerfile
    network_mode: 'host'
    volumes:
      - './backend:/app'
      - '/app/backend/node_modules'
    ports:
      - '4001:4000'

  mongoose:
    container_name: angl_db
    build:
      context: .
      dockerfile: backend/Dockerfile
    network_mode: 'host'
    volumes:
      - './backend/configs:/configs'
    ports:
      - '27018:27017'
